### ISSUE TITLE
Communication with a go-ipfs peer?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/js-libp2p-ipfs-browser#125]
As I understand, `js-libp2p2-ipfs-browser` allows for communication over WebRTC to another WebRTC node, browser-to-browser. Does this mean that `js-libp2p2-ipfs-browser` cannot directly communicate with a `go-ipfs` node? (My understanding is that `go-ipfs` has not implemented the WebRTC transport.)

**Comment by diasdavid** [comment]
@JustinDrake It can communicate through WebSockets or in the near future through Relay 

Hope it helped :)

**Comment by JustinDrake** [comment]
Thanks. Why is it that my `go-ipfs` crawler node can connect to ~200 peers, none of which are `js-ipfs`? Are there effectively two disjoint IPFS networks, one for `go-ipfs`, and one for `js-ipfs`?

**Comment by diasdavid** [comment]
@JustinDrake until go-ipfs 0.4.5 release happens, yes, they are disjoint networks
