### ISSUE TITLE
libp2p testing on metamask

### ISSUE THREAD

**Issue by kumavis** [ipfs/js-libp2p-ipfs-browser#127]
In the name of facilitating libp2p-based Ethereum light client development, we're planning to run some libp2p mesh testing in the live metamask extension.

Some Design Goals:

light: minimal overhead, gentle testing
safe: runs on a different domain than the extension (via iframe)
big: thousands of nodes
long: active mesh running for many consecutive days

@diasdavid please tag relevant contributors

previously tracking this on metamask issue: https://github.com/MetaMask/metamask-plugin/issues/719

**Comment by kumavis** [comment]
We need to identify:
- any blocking issues
- types of tests and metrics to gather
- test deployment procedure

**Comment by kumavis** [comment]
We will likely inject an iframe into the metamask background context that points at `https://metamask.github.io/libp2p-tests/` which should host a self-contained testing app.

**Comment by kumavis** [comment]
flood/pub sub test idea:
all peers could listen on the network for message X and report directly (via http) when they receive it to some stat gathering server

**Comment by diasdavid** [comment]
Let's get this set up during the DAppHackathon :) :)

**Comment by diasdavid** [comment]
Let's continue this convo at https://github.com/libp2p/js-libp2p/issues/106
