### ISSUE TITLE
Which transports are compatible with js-libp2p-browser?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/js-libp2p-ipfs-browser#192]
Which transports can js-libp2p-browser expect to use? As far as I can tell moderns browsers can support:

- WebSockets
- WebRTC

Did I miss any? I guess HTTP (?!) could maybe be used a transport (e.g. using `POST` requests).

**Comment by dryajov** [comment]
Those are the two, we could implement something on top of http, but so far I don't think it's neither a priority nor made particular sense given that the those two work in most/all cituations. Also, with circuit, we're going to be able to use relay nodes to communicate between nodes that don't talk the same protos, ie TCP only node wanting to communicate with browser node running on either WS or webrtc. Check out both the go and js repos - libp2p-circuit for status/progress.

**Comment by diasdavid** [comment]
@JustinDrake as @dryajov explaining, WS and WebRTC are the only ones currently supported. HTTP wouldn't add anything extra currently, but it is doable, yes :)

**Comment by JustinDrake** [comment]
Cool, thanks. Maybe an HTTP transport could be a fun project just to prove a point. :)
