### ISSUE TITLE
Support do dial to a multiaddr without peer-id

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-libp2p-ipfs-browser#83]
To achieve feature parity with go-ipfs (and therefore run the same interface-ipfs-core tests at the jsipfs swarm level)

**Comment by whyrusleeping** [comment]
You cannot dial to a peer (at least, a peer with secio enabled) without the peer ID in the multiaddr.

**Comment by diasdavid** [comment]
@whyrusleeping that sounds awesome and saves a lot of work, but look, go-ipfs supports it, this test passes in js-ipfs-api

https://github.com/ipfs/interface-ipfs-core/blob/master/src/swarm.js#L46-L52

The `id.addresses[0]` come from the output of the id command, which goes something like:

```
» ipfs id
{
        "ID": "QmQ2zigjQikYnyYUSXZydNXrDRhBut2mubwJBaLXobMt3A",
        "PublicKey": "CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2SKo/HMFZeBml1AF3XijzrxrfQXdJzjePBZAbdxqKR1Mc6juRHXij6HXYPjlAk01BhF1S3Ll4Lwi0cAHhggf457sMg55UWyeGKeUv0ucgvCpBwlR5cQ020i0MgzjPWOLWq1rtvSbNcAi2ZEVn6+Q2EcHo3wUvWRtLeKz+DZSZfw2PEDC+DGPJPl7f8g7zl56YymmmzH9liZLNrzg/qidokUv5u1pdGrcpLuPNeTODk0cqKB+OUbuKj9GShYECCEjaybJDl9276oalL9ghBtSeEv20kugatTvYy590wFlJkkvyl+nPxIH0EEYMKK9XRWlu9XYnoSfboiwcv8M3SlsjAgMBAAE=",
        "Addresses": [
                "/ip4/127.0.0.1/tcp/4001",
                "/ip4/192.168.1.156/tcp/4001",
                "/ip6/::/tcp/4001"
        ],
        "AgentVersion": "js-ipfs",
        "ProtocolVersion": "9000"
}
```

**Comment by diasdavid** [comment]
Ok, this is a bug in go-ipfs after all https://github.com/ipfs/go-ipfs/issues/3218
